### ISSUE TITLE
boom 了

### ISSUE THREAD

**Issue by tetsaicn** [KEN-LJQ/ZhihuSpider#6]
Traceback (most recent call last):
  File "startup.py", line 2, in <module>
    import core.ScrapeCore as ScrapeCore
  File "/home/yangyilang/ZhihuSpider/core/ScrapeCore.py", line 2, in <module>
    import core.DataFetch as DataFetch
  File "/home/yangyilang/ZhihuSpider/core/DataFetch.py", line 2, in <module>
    from proxy import proxyCore
  File "/home/yangyilang/ZhihuSpider/proxy/proxyCore.py", line 1, in <module>
    from proxy import validateData
  File "/home/yangyilang/ZhihuSpider/proxy/validateData.py", line 4, in <module>
    from proxy import proxyCore
ImportError: cannot import name 'proxyCore'

**Comment by KEN-LJQ** [comment]
代码中出现循环import了，但是我运行的时候没有出现过问题。你可以试着将‘ZhihuSpider/proxy/validateData.py’文件中第四行的`from proxy import proxyCore`放入到第29行的方法`validate_proxy_ip`里面。
![default](https://cloud.githubusercontent.com/assets/16650282/23999052/18637fd4-0a92-11e7-866d-b944e7a27fa0.PNG)

**Comment by tetsaicn** [comment]
这个，，，需要多少硬盘空间[整个知乎用户信息]

**Comment by KEN-LJQ** [comment]
没有把整个知乎用户信息爬完，只爬了30W，大小为85M左右

**Comment by tetsaicn** [comment]
还是无用
  File "startup.py", line 2, in <module>
    import core.ScrapeCore as ScrapeCore
  File "/home/yangyilang/ZhihuSpider/core/ScrapeCore.py", line 2, in <module>
    import core.DataFetch as DataFetch
  File "/home/yangyilang/ZhihuSpider/core/DataFetch.py", line 2, in <module>
    from proxy import proxyCore
  File "/home/yangyilang/ZhihuSpider/proxy/proxyCore.py", line 3, in <module>
    from proxy import parseData
  File "/home/yangyilang/ZhihuSpider/proxy/parseData.py", line 2, in <module>
    from proxy import proxyCore
ImportError: cannot import name 'proxyCore'

**Comment by tetsaicn** [comment]
顺便说一句我是Linux

**Comment by KEN-LJQ** [comment]
我在Centos上测试过了，也是没有问题。你可以把`/ZhihuSpider/proxy/parseData.py`这个文件修改后的代码放上来看看吗

**Comment by tetsaicn** [comment]
我修改的是‘ZhihuSpider/proxy/validateData.py’文件，'/ZhihuSpider/proxy/parseData.py'如下
from proxy import proxyCore
from bs4 import BeautifulSoup

class DataParseModule:
    def __init__(self):
        pass

    # 解析 DOM 内容
    @staticmethod
    def parse_data(data):
        # 存放解析出来代理信息
        proxy_ip_list = []

        # 判断数据是否为空
        if data is None:
            return proxy_ip_list

        # 解析获得包含代理 IP 的表格
        html = BeautifulSoup(data, "html.parser")
        html_ip_list = html.find('table', {'id': 'ip_list'})
        if html_ip_list is None:
            return proxy_ip_list
        data_list = html_ip_list.findAll('tr')

        # 逐个解析表格中的项
        for elem in data_list:
            if elem.find('th', text="国家") is not None:
                continue

            # 解析代理 IP 信息
            
            country_node = elem.find('td')
            ip_node = country_node.find_next_sibling()
            port_node = ip_node.find_next_sibling()
            protocol_node = port_node.find_next_sibling().find_next_sibling().find_next_sibling()
            ip = ip_node.string
            port = port_node.string
            protocol = protocol_node.string

            # 封装代理信息
            proxy_ip_info = {proxyCore.PROXY_IP: ip,
                             proxyCore.PROXY_PORT: port,
                             proxyCore.PROXY_PROTOCOL: protocol
                             }

            proxy_ip_list.append(proxy_ip_info)
        return proxy_ip_list

**Comment by KEN-LJQ** [comment]
同理，这个也将第2行的`from proxy import proxyCore`放入到第11行的`parse_data`方法的开头。
![default](https://cloud.githubusercontent.com/assets/16650282/24035463/a819907a-0b30-11e7-8cb9-4702fdb5c445.PNG)

**Comment by tetsaicn** [comment]
我试过啊，错误一堆

**Comment by tetsaicn** [comment]
Traceback (most recent call last):
  File "startup.py", line 6, in <module>
    spider = ScrapeCore.SpiderCore()
  File "/home/yangyilang/ZhihuSpider/core/ScrapeCore.py", line 248, in __init__
    self.userTokenCacheQueue = UserList.UserTokenCacheQueue(self.DBConnectModule)
  File "/home/yangyilang/ZhihuSpider/core/UserList.py", line 22, in __init__
    token_total = self.db_connection.get_user_token_num()
  File "/home/yangyilang/ZhihuSpider/core/DBConnector.py", line 134, in get_user_token_num
    cur.execute(COUNT_TOKEN)
  File "/usr/local/lib/python3.4/dist-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.4/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.4/dist-packages/pymysql/connections.py", line 852, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.4/dist-packages/pymysql/connections.py", line 1053, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.4/dist-packages/pymysql/connections.py", line 1336, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.4/dist-packages/pymysql/connections.py", line 1010, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.4/dist-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.4/dist-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'zhihu.user_list_cache' doesn't exist")
