### ISSUE TITLE
使用询问

### ISSUE THREAD

**Issue by tjyiiuan** [KEN-LJQ/ZhihuSpider#8]
您好，爬虫运行出现了如下错误：

F:\GITHUB\ZhihuSpider>python startup.py
Traceback (most recent call last):
  File "startup.py", line 1, in <module>
    from Core.SpiderCore import SpiderCore
  File "F:\GITHUB\ZhihuSpider\Core\SpiderCore.py", line 7, in <module>
    from Core.Logger import log
  File "F:\GITHUB\ZhihuSpider\Core\Logger.py", line 9, in <module>
    logging.config.fileConfig(configFile)
  File "F:\Anaconda2\lib\logging\config.py", line 84, in fileConfig
    handlers = _install_handlers(cp, formatters)
  File "F:\Anaconda2\lib\logging\config.py", line 148, in _install_handlers
    h = klass(*args)
  File "F:\Anaconda2\lib\logging\__init__.py", line 1025, in __init__
    StreamHandler.__init__(self, self._open())
  File "F:\Anaconda2\lib\logging\__init__.py", line 1054, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\GITHUB\\ZhihuSpider\\Logs\\ZhiHuSpider.log'

Python以及所有的库没问题，所以想问问是哪里出现了错误，谢谢

**Comment by KEN-LJQ** [comment]
你好，这是因为日志模块找不到对应的文件路径，你在`ZhihuSpider`目录下创建一个`Logs`文件夹就可以了

**Comment by tjyiiuan** [comment]
谢谢，这个问题解决了，现在的问题是：

raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to localhost:6379. 由于目标计算机积极拒绝，无法连接。。

请问是网络问题还是redis设置问题，或者是其他什么原因呢？谢谢！

**Comment by KEN-LJQ** [comment]
建议检查一下，需要连接的Redis服务器的IP地址，端口号以及密码是否正确
